annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Source
      url: https://github.com/promhippie/prometheus-vcd-sd
    - name: Chart
      url: https://github.com/promhippie/charts/tree/master/stable/prometheus-vcd-sd
  artifacthub.io/signKey: |
    fingerprint: B8BB213D9E131E46D2EBE22E44E93172C6FDE7E6
    url: https://raw.githubusercontent.com/promhippie/charts/master/promhippie.key
apiVersion: v2
appVersion: 2.2.4
description: A Helm chart for Prometheus VMWare vCloud Director SD
home: https://promhippie.github.io/prometheus-vcd-sd/
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/vmware.svg
keywords:
- vmware
- vcloud
- director
- prometheus
- sd
- service-discovery
maintainers:
- email: thomas@webhippie.de
  name: tboerger
  url: https://github.com/tboerger
name: prometheus-vcd-sd
sources:
- https://github.com/promhippie/prometheus-vcd-sd
type: application
version: 3.2.3
