---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: helmdocs

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  helmdocs:
    runs-on: ubuntu-latest
    if: github.repository == 'promhippie/charts'

    steps:
      - name: Checkout source
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Update readme
        id: docs
        uses: docker://jnorwood/helm-docs:v1.14.2@sha256:7e562b49ab6b1dbc50c3da8f2dd6ffa8a5c6bba327b1c6335cc15ce29267979c
        with:
          entrypoint: helm-docs

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: stable/
          message: "docs: automated readme updates [skip ci]"
          push: true
          commit: --signoff

...
