annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Source
      url: https://github.com/promhippie/prometheus-scw-sd
    - name: Chart
      url: https://github.com/promhippie/charts/tree/master/stable/prometheus-scw-sd
  artifacthub.io/signKey: |
    fingerprint: B8BB213D9E131E46D2EBE22E44E93172C6FDE7E6
    url: https://raw.githubusercontent.com/promhippie/charts/master/promhippie.key
apiVersion: v2
appVersion: 2.3.1
description: A Helm chart for Prometheus Scaleway SD
home: https://promhippie.github.io/prometheus-scw-sd/
icon: https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/scaleway.svg
keywords:
- scw
- scaleway
- prometheus
- sd
- service-discovery
maintainers:
- email: thomas@webhippie.de
  name: tboerger
  url: https://github.com/tboerger
name: prometheus-scw-sd
sources:
- https://github.com/promhippie/prometheus-scw-sd
type: application
version: 2.3.0
